AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - "Guardfile"
    - "Rakefile"
  DisplayCopNames: true

Layout/LineLength:
  Max: 150
Metrics/MethodLength:
  Max: 60
Metrics/AbcSize:
  Max: 50
Metrics/ClassLength:
  Max: 170
Metrics/BlockLength:
  ExcludedMethods: ["describe"]
  Max: 70
Metrics/AbcSize:
  Max: 130
Metrics/CyclomaticComplexity:
  Max: 70
Metrics/PerceivedComplexity:
  Max: 30
Style/Documentation:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Lint/ParenthesesAsGroupedExpression:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Layout/HashAlignment:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/TrailingWhitespace:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false

